apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tracker
data:
  DATA_DIR: "/data"
  DEBUG: "false"
  ALLOWED_HOSTS: "*"
  TRACKER_PRUNE_SECONDS: "60"
  TRACKER_DISCORD_WEBHOOK: ""
  TRACKER_DISCORD_ROLE_ID: ""
  TRACKER_DISCORD_NOTIFY_PASSWORDED: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tracker
  name: tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracker
  template:
    metadata:
      labels:
        app: tracker
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: tracker
      containers:
        - name: tracker
          image: "ghcr.io/avaraline/tracker"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: tracker
          ports:
            - containerPort: 8000
              protocol: TCP
          volumeMounts:
            - mountPath: "/data"
              name: data
---
apiVersion: v1
kind: Service
metadata:
  name: tracker
spec:
  selector:
    app: tracker
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
