# Generated by Django 3.2.13 on 2024-04-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_game_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='discord_msgid',
            field=models.TextField(blank=True),
        ),
    ]
